### PR TITLE
Re: Issue #10

### PR DESCRIPTION
**Pull request by aadityakhare**
Contribution to issue #11

### CODE REVIEW

**Comment by felipecustodio** [comment]
Hello, friend! 
@aadityakhare can you describe a little bit what you are adding? Thank you so much and good Hacktoberfesting!

**Comment by aadityakhare** [comment]
Well, I'd been working on a repository to add algorithms in 3 languages: C, Java, Python.
some of them are not in all 3 languages.
My addition has algorithms on the following:

- Searching and sorting (Binary, Radix, Selection, Shell, etc.
- Math (Armstrong no., tower of Hanoi, Integration, etc.)
- Cryptography ciphers (atbash, vigenere, etc.)
- Robotic Locomotion (PID, a*)

**Comment by felipecustodio** [comment]
@aadityakhare that is awesome! C is a powerful beast, we love it here at my college. 
I'm still a newbie to cryptography myself, what was your study strategy? Textbooks, internet resources? Have you used it in real world problems?

Thanks for the pull-request, I'll definitely take a look at the code. 👍

**Comment by aadityakhare** [comment]
@felipecustodio Yeah I love C too. Since my majors is Electronics and Communication, my resources for studying anything including cryptography in coding were mainly from the internet. Study strategy: never just read up on a concept and leave it there, do implement it and see how it works, what it does. I hunt for problems on sites like hackerrank and codechef and implemt it there.

**Pull request merged**
